name = "wallety"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_APP_URL = "https://wallety.pages.dev"

# Remova o comentário abaixo e configure quando usar Hyperdrive (conexão pooling)
# [[hyperdrive]]
# binding = "HYPERDRIVE"
# id = "seu-hyperdrive-id"
